// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zb2uLrpIHKtOKGu-T3PHNLLWDt512kE',
    appId: '1:773899499564:android:88295c1398f1fd9d38f989',
    messagingSenderId: '773899499564',
    projectId: 'elearning-97eb6',
    storageBucket: 'elearning-97eb6.appspot.com',
    measurementId: 'G-SLBEJ1L4P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4zb2uLrpIHKtOKGu-T3PHNLLWDt512kE',
    appId: '1:773899499564:android:88295c1398f1fd9d38f989',
    messagingSenderId: '773899499564',
    projectId: 'elearning-97eb6',
    storageBucket: 'elearning-97eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4zb2uLrpIHKtOKGu-T3PHNLLWDt512kE',
    appId: '1:773899499564:android:88295c1398f1fd9d38f989',
    messagingSenderId: '773899499564',
    projectId: 'elearning-97eb6',
    storageBucket: 'elearning-97eb6.appspot.com',
    androidClientId: '435353014562-nt0t3l9foeqotgglvm2fmstp0ujk7kqq.apps.googleusercontent.com',
    iosClientId: '435353014562-m7g03v0jei5giadla8qv43i4h8n89kfl.apps.googleusercontent.com',
    iosBundleId: 'id.edspert.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4zb2uLrpIHKtOKGu-T3PHNLLWDt512kE',
    appId: '1:773899499564:android:88295c1398f1fd9d38f989',
    messagingSenderId: '773899499564',
    projectId: 'elearning-97eb6',
    storageBucket: 'elearning-97eb6.appspot.com',
    androidClientId: '435353014562-nt0t3l9foeqotgglvm2fmstp0ujk7kqq.apps.googleusercontent.com',
    iosClientId: '435353014562-m7g03v0jei5giadla8qv43i4h8n89kfl.apps.googleusercontent.com',
    iosBundleId: 'id.edspert.elearning',
  );
}
